export const Popular = {
    title:"Popular Items",
    fItem1:'assets/img/food/fitem1.jpg',
    fItem2:'assets/img/food/fitem4.jpg',
    fItem3:'assets/img/food/fitem6.jpg',
    fItem4:'assets/img/food/fitem3.png',
    fItem5:'assets/img/food/fitem10.jpg',
    Price1:"99 INR",
    Price2:"120 INR",
    Price3:"150 INR",
    Price4:"180 INR",
    Price5:"210 INR",
    itemName1:"Chicken Pizza",
    itemName2:"Chicken Tikka Kebab",
    itemName3:"Fish Fry Roast",
    itemName4:"Chicken Tenders Fries",
    itemName5:"Veg Fried Rice",
}

export const TopRate = {
    title:"Top Rated Items",
    fItem1:'assets/img/food/fitem2.jpg',
    fItem2:'assets/img/food/fitem5.jpg',
    fItem3:'assets/img/food/fitem8.jpg',
    fItem4:'assets/img/food/fitem7.jpg',
    fItem5:'assets/img/food/fitem9.jpg',
    Price1:"99 INR",
    Price2:"190 INR",
    Price3:"150 INR",
    Price4:"210 INR",
    Price5:"310 INR",
    itemName1:"Chicken Fries",
    itemName2:"Grilled BBQ Chicken",
    itemName3:"Masala French Fries",
    itemName4:"prawns Fry Roast",
    itemName5:"Prawns Biryani",
}